
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on mesu2, at 2024-05-03 08:23:40.482932 by lepourh
*/

#ifndef __MaterialConst_DensityTable_DEF_H__
#define __MaterialConst_DensityTable_DEF_H__

#include <mpi.h>
#include <phase_map.h>

typedef struct {
 double density;
 PhaseMap map;
} MaterialConst_DensityTable;

typedef enum {
  DensityTable_density = 0,
  DensityTable_map
} MaterialConst_DensityTableTypeName;

extern const char MaterialConst_DensityTable_classname[];

extern const int MaterialConst_DensityTable_nmembers;

extern const size_t MaterialConst_DensityTable_member_sizes[];

extern const char *MaterialConst_DensityTable_member_names[];

extern MPI_Datatype MPI_MATERIALCONST_DENSITYTABLE;

/* prototypes */
void MaterialConst_DensityTableGetField_density(MaterialConst_DensityTable *point,double *data);
void MaterialConst_DensityTableGetField_map(MaterialConst_DensityTable *point,PhaseMap *data);
void MaterialConst_DensityTableSetField_density(MaterialConst_DensityTable *point,double data);
void MaterialConst_DensityTableSetField_map(MaterialConst_DensityTable *point,PhaseMap data);
void MaterialConst_DensityTableView(MaterialConst_DensityTable *point);
int MaterialConst_DensityTableCreateMPIDataType(MPI_Datatype *ptype);

#endif
