
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on mesu2, at 2024-05-03 08:23:40.482932 by lepourh
*/

#ifndef __MaterialConst_DensityTable_DEF_H__
#define __MaterialConst_DensityTable_DEF_H__

#include <mpi.h>

typedef struct {
 double density;
 char[40] mapname;
} MaterialConst_DensityTable;

typedef enum {
  DensityTable_density = 0,
  DensityTable_mapname
} MaterialConst_DensityTableTypeName;

extern const char MaterialConst_DensityTable_classname[];

extern const int MaterialConst_DensityTable_nmembers;

extern const size_t MaterialConst_DensityTable_member_sizes[];

extern const char *MaterialConst_DensityTable_member_names[];

extern MPI_Datatype MPI_MATERIALCONST_DENSITYTABLE;

/* prototypes */
void MaterialConst_DensityTableGetField_density(MaterialConst_DensityTable *point,double *data);
void MaterialConst_DensityTableGetField_mapname(MaterialConst_DensityTable *point,char[40] *data);
void MaterialConst_DensityTableSetField_density(MaterialConst_DensityTable *point,double data);
void MaterialConst_DensityTableSetField_mapname(MaterialConst_DensityTable *point,char[40] data);
void MaterialConst_DensityTableView(MaterialConst_DensityTable *point);
void MaterialConst_DensityTableVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityTable points[]);
void MaterialConst_DensityTablePVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_DensityTableVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_DensityTable points[]);
void MaterialConst_DensityTableVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityTable points[]);
int MaterialConst_DensityTableCreateMPIDataType(MPI_Datatype *ptype);

#endif
