
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on lifou, at 2024-09-10 16:44:24.766622 by jourdon
*/

#ifndef __MaterialConst_PlasticMises_DEF_H__
#define __MaterialConst_PlasticMises_DEF_H__

#include <mpi.h>

typedef struct {
 double tau_yield;
 double tau_yield_inf;
 double healing_rate;
} MaterialConst_PlasticMises;

typedef enum {
  PlasticMises_yield_stress = 0,
  PlasticMises_yield_stress_inf,
  PlasticMises_healing_rate
} MaterialConst_PlasticMisesTypeName;

extern const char MaterialConst_PlasticMises_classname[];

extern const int MaterialConst_PlasticMises_nmembers;

extern const size_t MaterialConst_PlasticMises_member_sizes[];

extern const char *MaterialConst_PlasticMises_member_names[];

extern MPI_Datatype MPI_MATERIALCONST_PLASTICMISES;

/* prototypes */
void MaterialConst_PlasticMisesGetField_yield_stress(MaterialConst_PlasticMises *point,double *data);
void MaterialConst_PlasticMisesGetField_yield_stress_inf(MaterialConst_PlasticMises *point,double *data);
void MaterialConst_PlasticMisesGetField_healing_rate(MaterialConst_PlasticMises *point,double *data);
void MaterialConst_PlasticMisesSetField_yield_stress(MaterialConst_PlasticMises *point,double data);
void MaterialConst_PlasticMisesSetField_yield_stress_inf(MaterialConst_PlasticMises *point,double data);
void MaterialConst_PlasticMisesSetField_healing_rate(MaterialConst_PlasticMises *point,double data);
void MaterialConst_PlasticMisesView(MaterialConst_PlasticMises *point);
void MaterialConst_PlasticMisesVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_PlasticMises points[]);
void MaterialConst_PlasticMisesPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_PlasticMisesVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_PlasticMises points[]);
void MaterialConst_PlasticMisesVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_PlasticMises points[]);
int MaterialConst_PlasticMisesCreateMPIDataType(MPI_Datatype *ptype);

#endif
