/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on DESKTOP-S1BGS4R, at 2024-02-13 18:23:35.400149 by tony
*/

#ifndef __MaterialConst_ViscosityArrh_DislDiff_DEF_H__
#define __MaterialConst_ViscosityArrh_DislDiff_DEF_H__

#include <mpi.h>

typedef struct {
 double preexpA_disl;
 double Ascale_disl;
 double entalpy_disl;
 double Vmol_disl;
 double nexp_disl;
 double preexpA_diff;
 double Ascale_diff;
 double entalpy_diff;
 double Vmol_diff;
 double pexp_diff;
 double gsize;
 double Tref;
 double Eta_scale;
 double P_scale;
} MaterialConst_ViscosityArrh_DislDiff;

typedef enum {
  ViscosityArrh_DislDiff_preexpA_disl = 0,
  ViscosityArrh_DislDiff_Ascale_disl,
  ViscosityArrh_DislDiff_entalpy_disl,
  ViscosityArrh_DislDiff_Vmol_disl,
  ViscosityArrh_DislDiff_nexp_disl,
  ViscosityArrh_DislDiff_preexpA_diff,
  ViscosityArrh_DislDiff_Ascale_diff,
  ViscosityArrh_DislDiff_entalpy_diff,
  ViscosityArrh_DislDiff_Vmol_diff,
  ViscosityArrh_DislDiff_pexp_diff,
  ViscosityArrh_DislDiff_gsize,
  ViscosityArrh_DislDiff_Tref,
  ViscosityArrh_DislDiff_Eta_scale,
  ViscosityArrh_DislDiff_P_scale
} MaterialConst_ViscosityArrh_DislDiffTypeName;

extern const char MaterialConst_ViscosityArrh_DislDiff_classname[];

extern const int MaterialConst_ViscosityArrh_DislDiff_nmembers;

extern const size_t MaterialConst_ViscosityArrh_DislDiff_member_sizes[];

extern const char *MaterialConst_ViscosityArrh_DislDiff_member_names[];

extern MPI_Datatype MPI_MATERIALCONST_VISCOSITYARRH_DISLDIFF;

/* prototypes */
void MaterialConst_ViscosityArrh_DislDiffGetField_preexpA_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_Ascale_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_entalpy_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_Vmol_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_nexp_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_preexpA_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_Ascale_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_entalpy_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_Vmol_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_pexp_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_gsize(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_Tref(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_Eta_scale(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffGetField_P_scale(MaterialConst_ViscosityArrh_DislDiff *point,double *data);
void MaterialConst_ViscosityArrh_DislDiffSetField_preexpA_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_Ascale_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_entalpy_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_Vmol_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_nexp_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_preexpA_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_Ascale_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_entalpy_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_Vmol_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_pexp_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_gsize(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_Tref(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_Eta_scale(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffSetField_P_scale(MaterialConst_ViscosityArrh_DislDiff *point,double data);
void MaterialConst_ViscosityArrh_DislDiffView(MaterialConst_ViscosityArrh_DislDiff *point);
void MaterialConst_ViscosityArrh_DislDiffVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityArrh_DislDiff points[]);
void MaterialConst_ViscosityArrh_DislDiffPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MaterialConst_ViscosityArrh_DislDiffVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_ViscosityArrh_DislDiff points[]);
void MaterialConst_ViscosityArrh_DislDiffVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityArrh_DislDiff points[]);
int MaterialConst_ViscosityArrh_DislDiffCreateMPIDataType(MPI_Datatype *ptype);

#endif
