/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on DESKTOP-S1BGS4R, at 2024-02-13 18:23:35.400907 by tony
*/

#include <stdio.h>
#include <string.h>
#include <mpi.h>

#include "MaterialConst_ViscosityArrh_DislDiff_def.h"


const char MaterialConst_ViscosityArrh_DislDiff_classname[] = "MaterialConst_ViscosityArrh_DislDiff";

const int MaterialConst_ViscosityArrh_DislDiff_nmembers = 14;

const size_t MaterialConst_ViscosityArrh_DislDiff_member_sizes[] = {
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double),
  1 * sizeof(double)
};

const char *MaterialConst_ViscosityArrh_DislDiff_member_names[] = {
  "preexpA_disl",
  "Ascale_disl",
  "entalpy_disl",
  "Vmol_disl",
  "nexp_disl",
  "preexpA_diff",
  "Ascale_diff",
  "entalpy_diff",
  "Vmol_diff",
  "pexp_diff",
  "gsize",
  "Tref",
  "Eta_scale",
  "P_scale"
};

MPI_Datatype MPI_MATERIALCONST_VISCOSITYARRH_DISLDIFF;


/* ===================================== */
/* Getters for MaterialConst_ViscosityArrh_DislDiff */
/* ===================================== */
void MaterialConst_ViscosityArrh_DislDiffGetField_preexpA_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->preexpA_disl;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_Ascale_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->Ascale_disl;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_entalpy_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->entalpy_disl;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_Vmol_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->Vmol_disl;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_nexp_disl(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->nexp_disl;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_preexpA_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->preexpA_diff;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_Ascale_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->Ascale_diff;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_entalpy_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->entalpy_diff;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_Vmol_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->Vmol_diff;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_pexp_diff(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->pexp_diff;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_gsize(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->gsize;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_Tref(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->Tref;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_Eta_scale(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->Eta_scale;
}

void MaterialConst_ViscosityArrh_DislDiffGetField_P_scale(MaterialConst_ViscosityArrh_DislDiff *point,double *data) 
{
  *data = point->P_scale;
}


/* ===================================== */
/* Setters for MaterialConst_ViscosityArrh_DislDiff */
/* ===================================== */
void MaterialConst_ViscosityArrh_DislDiffSetField_preexpA_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->preexpA_disl = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_Ascale_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->Ascale_disl = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_entalpy_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->entalpy_disl = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_Vmol_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->Vmol_disl = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_nexp_disl(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->nexp_disl = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_preexpA_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->preexpA_diff = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_Ascale_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->Ascale_diff = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_entalpy_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->entalpy_diff = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_Vmol_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->Vmol_diff = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_pexp_diff(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->pexp_diff = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_gsize(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->gsize = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_Tref(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->Tref = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_Eta_scale(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->Eta_scale = data;
}

void MaterialConst_ViscosityArrh_DislDiffSetField_P_scale(MaterialConst_ViscosityArrh_DislDiff *point,double data) 
{
  point->P_scale = data;
}


/* ===================================== */
/* C-viewer for MaterialConst_ViscosityArrh_DislDiff */
/* ===================================== */
void MaterialConst_ViscosityArrh_DislDiffView(MaterialConst_ViscosityArrh_DislDiff *point)
{
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_preexpA_disl(point,&data);
    printf("field: preexpA_disl = %1.6e; [size %zu; type double; variable_name preexpA_disl]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[0] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_Ascale_disl(point,&data);
    printf("field: Ascale_disl = %1.6e; [size %zu; type double; variable_name Ascale_disl]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[1] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_entalpy_disl(point,&data);
    printf("field: entalpy_disl = %1.6e; [size %zu; type double; variable_name entalpy_disl]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[2] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_Vmol_disl(point,&data);
    printf("field: Vmol_disl = %1.6e; [size %zu; type double; variable_name Vmol_disl]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[3] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_nexp_disl(point,&data);
    printf("field: nexp_disl = %1.6e; [size %zu; type double; variable_name nexp_disl]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[4] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_preexpA_diff(point,&data);
    printf("field: preexpA_diff = %1.6e; [size %zu; type double; variable_name preexpA_diff]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[5] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_Ascale_diff(point,&data);
    printf("field: Ascale_diff = %1.6e; [size %zu; type double; variable_name Ascale_diff]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[6] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_entalpy_diff(point,&data);
    printf("field: entalpy_diff = %1.6e; [size %zu; type double; variable_name entalpy_diff]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[7] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_Vmol_diff(point,&data);
    printf("field: Vmol_diff = %1.6e; [size %zu; type double; variable_name Vmol_diff]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[8] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_pexp_diff(point,&data);
    printf("field: pexp_diff = %1.6e; [size %zu; type double; variable_name pexp_diff]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[9] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_gsize(point,&data);
    printf("field: gsize = %1.6e; [size %zu; type double; variable_name gsize]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[10] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_Tref(point,&data);
    printf("field: Tref = %1.6e; [size %zu; type double; variable_name Tref]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[11] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_Eta_scale(point,&data);
    printf("field: Eta_scale = %1.6e; [size %zu; type double; variable_name Eta_scale]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[12] );
  }
  {
    double data;
    MaterialConst_ViscosityArrh_DislDiffGetField_P_scale(point,&data);
    printf("field: P_scale = %1.6e; [size %zu; type double; variable_name P_scale]\n",data, MaterialConst_ViscosityArrh_DislDiff_member_sizes[13] );
  }
}


/* ===================================== */
/* VTK viewer for MaterialConst_ViscosityArrh_DislDiff */
/* ===================================== */
void MaterialConst_ViscosityArrh_DislDiffVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityArrh_DislDiff points[]) 
{
  int p;
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"preexpA_disl\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].preexpA_disl);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Ascale_disl\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Ascale_disl);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"entalpy_disl\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].entalpy_disl);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Vmol_disl\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Vmol_disl);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"nexp_disl\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].nexp_disl);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"preexpA_diff\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].preexpA_diff);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Ascale_diff\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Ascale_diff);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"entalpy_diff\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].entalpy_diff);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Vmol_diff\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Vmol_diff);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"pexp_diff\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].pexp_diff);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"gsize\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].gsize);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Tref\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Tref);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Eta_scale\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].Eta_scale);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"P_scale\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].P_scale);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
}


/* ===================================== */
/* PVTU viewer for MaterialConst_ViscosityArrh_DislDiff */
/* ===================================== */
void MaterialConst_ViscosityArrh_DislDiffPVTUWriteAllPPointDataFields(FILE *vtk_fp) 
{
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"preexpA_disl\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Ascale_disl\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"entalpy_disl\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Vmol_disl\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"nexp_disl\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"preexpA_diff\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Ascale_diff\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"entalpy_diff\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Vmol_diff\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"pexp_diff\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"gsize\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Tref\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"Eta_scale\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float64\" Name=\"P_scale\" NumberOfComponents=\"1\"/>\n");
}


/* ===================================== */
/* VTK binary (appended header) viewer for MaterialConst_ViscosityArrh_DislDiff */
/* ===================================== */
void MaterialConst_ViscosityArrh_DislDiffVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MaterialConst_ViscosityArrh_DislDiff points[]) 
{
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"preexpA_disl\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Ascale_disl\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"entalpy_disl\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Vmol_disl\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"nexp_disl\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"preexpA_diff\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Ascale_diff\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"entalpy_diff\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Vmol_diff\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"pexp_diff\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"gsize\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Tref\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"Eta_scale\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"P_scale\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(double);

}


/* ================================================== */
/* VTK binary (appended data) viewer for MaterialConst_ViscosityArrh_DislDiff */
/* ==================================================== */
void MaterialConst_ViscosityArrh_DislDiffVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MaterialConst_ViscosityArrh_DislDiff points[]) 
{
  int p,length;
  size_t atomic_size;

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].preexpA_disl,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Ascale_disl,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].entalpy_disl,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Vmol_disl,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].nexp_disl,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].preexpA_diff,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Ascale_diff,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].entalpy_diff,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Vmol_diff,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].pexp_diff,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].gsize,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Tref,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Eta_scale,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(double);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].P_scale,atomic_size,1,vtk_fp);
  }

}


/* ===================================== */
/* MPI data type for MaterialConst_ViscosityArrh_DislDiff */
/* ===================================== */
int MaterialConst_ViscosityArrh_DislDiffCreateMPIDataType(MPI_Datatype *ptype)
{
  MPI_Datatype newtype;
  MPI_Datatype types[] = { MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE , MPI_DOUBLE };
  int blocklens[] = { 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 };
  MPI_Aint loc[15];
  MPI_Aint disp[14];
  MaterialConst_ViscosityArrh_DislDiff dummy;
  int i,ierr;

  ierr = MPI_Get_address(&dummy,&loc[0]);
  ierr = MPI_Get_address(&dummy.preexpA_disl,&loc[1]);
  ierr = MPI_Get_address(&dummy.Ascale_disl,&loc[2]);
  ierr = MPI_Get_address(&dummy.entalpy_disl,&loc[3]);
  ierr = MPI_Get_address(&dummy.Vmol_disl,&loc[4]);
  ierr = MPI_Get_address(&dummy.nexp_disl,&loc[5]);
  ierr = MPI_Get_address(&dummy.preexpA_diff,&loc[6]);
  ierr = MPI_Get_address(&dummy.Ascale_diff,&loc[7]);
  ierr = MPI_Get_address(&dummy.entalpy_diff,&loc[8]);
  ierr = MPI_Get_address(&dummy.Vmol_diff,&loc[9]);
  ierr = MPI_Get_address(&dummy.pexp_diff,&loc[10]);
  ierr = MPI_Get_address(&dummy.gsize,&loc[11]);
  ierr = MPI_Get_address(&dummy.Tref,&loc[12]);
  ierr = MPI_Get_address(&dummy.Eta_scale,&loc[13]);
  ierr = MPI_Get_address(&dummy.P_scale,&loc[14]);

  for (i=0; i<14; i++) {
    disp[i] = loc[i+1] - loc[0];
  }

  ierr = MPI_Type_create_struct(14,blocklens,disp,types,&newtype);
  ierr = MPI_Type_commit(&newtype);
  *ptype = newtype;
  return 0;
}

