
/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on mesu2, at 2024-05-03 08:23:40.484017 by lepourh
*/

#include <stdio.h>
#include <string.h>
#include <mpi.h>

#include "MaterialConst_DensityTable_def.h"


const char MaterialConst_DensityTable_classname[] = "MaterialConst_DensityTable";

const int MaterialConst_DensityTable_nmembers = 2;

const size_t MaterialConst_DensityTable_member_sizes[] = {
  1 * sizeof(double),
  1 * sizeof(char[40])
};

const char *MaterialConst_DensityTable_member_names[] = {
  "density",
  "mapname"
};

MPI_Datatype MPI_MATERIALCONST_DENSITYTABLE;


/* ===================================== */
/* Getters for MaterialConst_DensityTable */
/* ===================================== */
void MaterialConst_DensityTableGetField_density(MaterialConst_DensityTable *point,double *data) 
{
  *data = point->density;
}

void MaterialConst_DensityTableGetField_mapname(MaterialConst_DensityTable *point,char[40] *data) 
{
  *data = point->mapname;
}


/* ===================================== */
/* Setters for MaterialConst_DensityTable */
/* ===================================== */
void MaterialConst_DensityTableSetField_density(MaterialConst_DensityTable *point,double data) 
{
  point->density = data;
}

void MaterialConst_DensityTableSetField_mapname(MaterialConst_DensityTable *point,char[40] data) 
{
  point->mapname = data;
}


/* ===================================== */
/* C-viewer for MaterialConst_DensityTable */
/* ===================================== */
void MaterialConst_DensityTableView(MaterialConst_DensityTable *point)
{
  {
    double data;
    MaterialConst_DensityTableGetField_density(point,&data);
    printf("field: density = %1.6e; [size %zu; type double; variable_name density]\n",data, MaterialConst_DensityTable_member_sizes[0] );
  }
  {
    char[40] data;
    MaterialConst_DensityTableGetField_mapname(point,&data);
    printf("field: mapname = ; [size %zu; type char[40]; variable_name mapname]\n",data, MaterialConst_DensityTable_member_sizes[1] );
  }
}


/* ===================================== */
/* VTK viewer for MaterialConst_DensityTable */
/* ===================================== */
void MaterialConst_DensityTableVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MaterialConst_DensityTable points[]) 
{
  int p;
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float64\" Name=\"density\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%lf\n",(double)points[p].density);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
Unknown type: Cannot find equivalent VTKType
