/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on otsu.local, at 2024-11-14 11:51:29.335556 by dmay
*/

#ifndef __MPntPEnergy_DEF_H__
#define __MPntPEnergy_DEF_H__

#include <mpi.h>

typedef struct {
 double diffusivity;
 double heat_source;
 double heat_source_init;
} MPntPEnergy;

typedef enum {
  MPPEgy_diffusivity = 0,
  MPPEgy_heat_source,
  MPPEgy_heat_source_init
} MPntPEnergyTypeName;

extern const char MPntPEnergy_classname[];

extern const int MPntPEnergy_nmembers;

extern const size_t MPntPEnergy_member_sizes[];

extern const char *MPntPEnergy_member_names[];

extern MPI_Datatype MPI_MPNTPENERGY;

/* prototypes */
void MPntPEnergyGetField_diffusivity(MPntPEnergy *point,double *data);
void MPntPEnergyGetField_heat_source(MPntPEnergy *point,double *data);
void MPntPEnergyGetField_heat_source_init(MPntPEnergy *point,double *data);
void MPntPEnergySetField_diffusivity(MPntPEnergy *point,double data);
void MPntPEnergySetField_heat_source(MPntPEnergy *point,double data);
void MPntPEnergySetField_heat_source_init(MPntPEnergy *point,double data);
void MPntPEnergyView(MPntPEnergy *point);
void MPntPEnergyVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MPntPEnergy points[]);
void MPntPEnergyPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MPntPEnergyVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MPntPEnergy points[]);
void MPntPEnergyVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MPntPEnergy points[]);
int MPntPEnergyCreateMPIDataType(MPI_Datatype *ptype);

#endif
