/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on otsu.local, at 2024-11-14 11:51:29.335406 by dmay
*/

#ifndef __MPntPStokesPl_DEF_H__
#define __MPntPStokesPl_DEF_H__

#include <mpi.h>

typedef struct {
 float e_plastic;
 short is_yielding;
 float damage;
} MPntPStokesPl;

typedef enum {
  MPPStkPl_plastic_strain = 0,
  MPPStkPl_yield_indicator,
  MPPStkPl_damage
} MPntPStokesPlTypeName;

extern const char MPntPStokesPl_classname[];

extern const int MPntPStokesPl_nmembers;

extern const size_t MPntPStokesPl_member_sizes[];

extern const char *MPntPStokesPl_member_names[];

extern MPI_Datatype MPI_MPNTPSTOKESPL;

/* prototypes */
void MPntPStokesPlGetField_plastic_strain(MPntPStokesPl *point,float *data);
void MPntPStokesPlGetField_yield_indicator(MPntPStokesPl *point,short *data);
void MPntPStokesPlGetField_damage(MPntPStokesPl *point,float *data);
void MPntPStokesPlSetField_plastic_strain(MPntPStokesPl *point,float data);
void MPntPStokesPlSetField_yield_indicator(MPntPStokesPl *point,short data);
void MPntPStokesPlSetField_damage(MPntPStokesPl *point,float data);
void MPntPStokesPlView(MPntPStokesPl *point);
void MPntPStokesPlVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MPntPStokesPl points[]);
void MPntPStokesPlPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void MPntPStokesPlVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MPntPStokesPl points[]);
void MPntPStokesPlVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MPntPStokesPl points[]);
int MPntPStokesPlCreateMPIDataType(MPI_Datatype *ptype);

#endif
