/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on otsu.local, at 2024-11-15 08:15:39.864235 by dmay
*/

#ifndef __QPntVolCoefEnergy_DEF_H__
#define __QPntVolCoefEnergy_DEF_H__

#include <mpi.h>

typedef struct {
 double diffusivity;
 double heat_source;
} QPntVolCoefEnergy;

typedef enum {
  QPVCEgy_diffusivity = 0,
  QPVCEgy_heat_source
} QPntVolCoefEnergyTypeName;

extern const char QPntVolCoefEnergy_classname[];

extern const int QPntVolCoefEnergy_nmembers;

extern const size_t QPntVolCoefEnergy_member_sizes[];

extern const char *QPntVolCoefEnergy_member_names[];

extern MPI_Datatype MPI_QPNTVOLCOEFENERGY;

/* prototypes */
void QPntVolCoefEnergyGetField_diffusivity(QPntVolCoefEnergy *point,double *data);
void QPntVolCoefEnergyGetField_heat_source(QPntVolCoefEnergy *point,double *data);
void QPntVolCoefEnergySetField_diffusivity(QPntVolCoefEnergy *point,double data);
void QPntVolCoefEnergySetField_heat_source(QPntVolCoefEnergy *point,double data);
void QPntVolCoefEnergyView(QPntVolCoefEnergy *point);
void QPntVolCoefEnergyVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const QPntVolCoefEnergy points[]);
void QPntVolCoefEnergyPVTUWriteAllPPointDataFields(FILE *vtk_fp);
void QPntVolCoefEnergyVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const QPntVolCoefEnergy points[]);
void QPntVolCoefEnergyVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const QPntVolCoefEnergy points[]);
int QPntVolCoefEnergyCreateMPIDataType(MPI_Datatype *ptype);

#endif
