/*
  Auto generated by version 0.0 of swarm_class_generator.py
  on DESKTOP-4R168SI, at 2022-06-30 09:49:44.405567 by tony
*/

#include <stdio.h>
#include <string.h>
#include <mpi.h>

#include "MPntPChrono_def.h"


const char MPntPChrono_classname[] = "MPntPChrono";

const int MPntPChrono_nmembers = 4;

const size_t MPntPChrono_member_sizes[] = {
  1 * sizeof(float),
  1 * sizeof(float),
  1 * sizeof(float),
  1 * sizeof(float)
};

const char *MPntPChrono_member_names[] = {
  "age120",
  "age350",
  "age800",
  "Tmax"
};

MPI_Datatype MPI_MPNTPCHRONO;


/* ===================================== */
/* Getters for MPntPChrono */
/* ===================================== */
void MPntPChronoGetField_age120(MPntPChrono *point,float *data) 
{
  *data = point->age120;
}

void MPntPChronoGetField_age350(MPntPChrono *point,float *data) 
{
  *data = point->age350;
}

void MPntPChronoGetField_age800(MPntPChrono *point,float *data) 
{
  *data = point->age800;
}

void MPntPChronoGetField_Tmax(MPntPChrono *point,float *data) 
{
  *data = point->Tmax;
}


/* ===================================== */
/* Setters for MPntPChrono */
/* ===================================== */
void MPntPChronoSetField_age120(MPntPChrono *point,float data) 
{
  point->age120 = data;
}

void MPntPChronoSetField_age350(MPntPChrono *point,float data) 
{
  point->age350 = data;
}

void MPntPChronoSetField_age800(MPntPChrono *point,float data) 
{
  point->age800 = data;
}

void MPntPChronoSetField_Tmax(MPntPChrono *point,float data) 
{
  point->Tmax = data;
}


/* ===================================== */
/* C-viewer for MPntPChrono */
/* ===================================== */
void MPntPChronoView(MPntPChrono *point)
{
  {
    float data;
    MPntPChronoGetField_age120(point,&data);
    printf("field: age120 = %1.6e; [size %zu; type float; variable_name age120]\n",data, MPntPChrono_member_sizes[0] );
  }
  {
    float data;
    MPntPChronoGetField_age350(point,&data);
    printf("field: age350 = %1.6e; [size %zu; type float; variable_name age350]\n",data, MPntPChrono_member_sizes[1] );
  }
  {
    float data;
    MPntPChronoGetField_age800(point,&data);
    printf("field: age800 = %1.6e; [size %zu; type float; variable_name age800]\n",data, MPntPChrono_member_sizes[2] );
  }
  {
    float data;
    MPntPChronoGetField_Tmax(point,&data);
    printf("field: Tmax = %1.6e; [size %zu; type float; variable_name Tmax]\n",data, MPntPChrono_member_sizes[3] );
  }
}


/* ===================================== */
/* VTK viewer for MPntPChrono */
/* ===================================== */
void MPntPChronoVTKWriteAsciiAllFields(FILE *vtk_fp,const int N,const MPntPChrono points[]) 
{
  int p;
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"age120\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%f\n",(float)points[p].age120);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"age350\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%f\n",(float)points[p].age350);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"age800\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%f\n",(float)points[p].age800);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"Tmax\" format=\"ascii\">\n");
  for(p=0;p<N;p++) {
    fprintf( vtk_fp,"\t\t\t\t\t%f\n",(float)points[p].Tmax);
  }
  fprintf( vtk_fp, "\t\t\t\t</DataArray>\n");
}


/* ===================================== */
/* PVTU viewer for MPntPChrono */
/* ===================================== */
void MPntPChronoPVTUWriteAllPPointDataFields(FILE *vtk_fp) 
{
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float32\" Name=\"age120\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float32\" Name=\"age350\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float32\" Name=\"age800\" NumberOfComponents=\"1\"/>\n");
  fprintf(vtk_fp, "\t\t\t<PDataArray type=\"Float32\" Name=\"Tmax\" NumberOfComponents=\"1\"/>\n");
}


/* ===================================== */
/* VTK binary (appended header) viewer for MPntPChrono */
/* ===================================== */
void MPntPChronoVTKWriteBinaryAppendedHeaderAllFields(FILE *vtk_fp,int *offset,const int N,const MPntPChrono points[]) 
{
  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"age120\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(float);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"age350\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(float);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"age800\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(float);

  fprintf( vtk_fp, "\t\t\t\t<DataArray type=\"Float32\" Name=\"Tmax\" format=\"appended\"  offset=\"%d\" />\n",*offset);
  *offset = *offset + sizeof(int) + N * sizeof(float);

}


/* ================================================== */
/* VTK binary (appended data) viewer for MPntPChrono */
/* ==================================================== */
void MPntPChronoVTKWriteBinaryAppendedDataAllFields(FILE *vtk_fp,const int N,const MPntPChrono points[]) 
{
  int p,length;
  size_t atomic_size;

  atomic_size = sizeof(float);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].age120,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(float);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].age350,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(float);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].age800,atomic_size,1,vtk_fp);
  }

  atomic_size = sizeof(float);
  length = (int)( atomic_size * ((size_t)N) );
  fwrite( &length,sizeof(int),1,vtk_fp);
  for(p=0;p<N;p++) {
    fwrite( &points[p].Tmax,atomic_size,1,vtk_fp);
  }

}


/* ===================================== */
/* MPI data type for MPntPChrono */
/* ===================================== */
int MPntPChronoCreateMPIDataType(MPI_Datatype *ptype)
{
  MPI_Datatype newtype;
  MPI_Datatype types[] = { MPI_FLOAT , MPI_FLOAT , MPI_FLOAT , MPI_FLOAT };
  int blocklens[] = { 1 , 1 , 1 , 1 };
  MPI_Aint loc[5];
  MPI_Aint disp[4];
  MPntPChrono dummy;
  int i,ierr;

  ierr = MPI_Get_address(&dummy,&loc[0]);
  ierr = MPI_Get_address(&dummy.age120,&loc[1]);
  ierr = MPI_Get_address(&dummy.age350,&loc[2]);
  ierr = MPI_Get_address(&dummy.age800,&loc[3]);
  ierr = MPI_Get_address(&dummy.Tmax,&loc[4]);

  for (i=0; i<4; i++) {
    disp[i] = loc[i+1] - loc[0];
  }

  ierr = MPI_Type_create_struct(4,blocklens,disp,types,&newtype);
  ierr = MPI_Type_commit(&newtype);
  *ptype = newtype;
  return 0;
}

